### ISSUE TITLE
タブの画像の準備

### ISSUE THREAD

**Issue by SatoTatsuhiro** [shin-kanouchi/SLOT_iOS#10]
# 天井情報の画像
- [x] 30×30
- [x] 60×60
- [x] 90×90

# 協力ブログの画像
- [x] 30×30
- [x] 60×60
- [x] 90×90

# 便利ツールの画像
- [x] 30×30
- [x] 60×60
- [x] 90×90

**Comment by shin-kanouchi** [comment]
finish!

**Comment by SatoTatsuhiro** [comment]
:+1:

**Comment by SatoTatsuhiro** [comment]
@shin-kanouchi リンクここに貼ってくれたら左藤嬉しい！！
