### ISSUE TITLE
狙い目ラベル

### ISSUE THREAD

**Issue by shin-kanouchi** [shin-kanouchi/SLOT_iOS#16]
# やること
テーブルビューの狙い目のところに狙い目ラベルを追加．

狙い目ラベルはDBに機種ごとに入っている．

# 狙い目ラベル の種類
1. 通常時 
2. ボーナス間 
3. AT間 
4. ART間
5. 天井まで残り
6. その他

6のその他は，その狙い目ラベルに何も表示しなくておけかも．

**Comment by shin-kanouchi** [comment]
狙い目ラベルはやっぱり複雑にしない．

文字列を入れられるように変更
(現在は数字)

**Comment by SatoTatsuhiro** [comment]
終了したのでクローズ
